services:

  postgres:
    container_name: psql
    image: postgres:14.1
    env_file: "./.env.yml"
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  spring-api:
    container_name: spring-boot
    build:
      context: ./spring-api
      dockerfile: Dockerfile
    env_file: "./.env.yml"
    ports:
      - "8080:8080"

  react-ui:
    container_name: react-ui
    build:
      context: ./react-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  psql: