services:

  postgres:
    container_name: psql
    image: postgres:14.1
    env_file: ".env.yaml"
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  spring-api:
    container_name: spring-boot
    image: spring-api:latest
    env_file: ".env.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped

  react-ui:
    container_name: react-ui
    image: react-ui:latest
    ports:
      - "3000:3000"

volumes:
  psql: