spring:
  application:
    name: Medical Booking
  datasource:
    url: jdbc:postgresql://localhost:5332/booking
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

okta: 
  oauth2: 
    issuer: ${ISSUER}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

server:
  error:
    include-message: always
